#docs = rbind( docs, c("c1", "Human machine interface for Lab ABC computer applications"))
#docs = rbind( docs, c("c2", "A survey of user opinion of computer system response time"))
#docs = rbind( docs, c("c3", "The EPS user interface management system"))
#docs = rbind( docs, c("c4", "System and human system engineering testing of EPS"))
#docs = rbind( docs, c("c5", "Relation of user-perceived response time to error measurement"))
#docs = rbind( docs, c("m1", "The generation of random, binary, unordered trees"))
#docs = rbind( docs, c("m2", "The intersection graph of paths in trees"))
#docs = rbind( docs, c("m3", "Graph minors IV: Widths of trees and well-quasi-ordering"))
#docs = rbind( docs, c("m4", "Graph minors: A survey"))
#docs = rbind( docs, c("p1", "Learning: the intersection with organisational knowledge"))
#docs = rbind( docs, c("p2", "A transactional perspective on teaching and learning"))
#docs = rbind( docs, c("p3", "Innovations in online learning: moving beyond no significant difference"))
#docs = rbind( docs, c("p4", "Tacit knowledge: the management of organisational learning and innovation"))
#docs = rbind( docs, c("p5", "Knowledge building: theory, pedagogy, and technology"))

# old
#docs = rbind( docs, c("c1", "a web interface for social media applications")) # web social interface
#docs = rbind( docs, c("c2", "Review of access time restrictions to web system usage")) # web access review system time user
#docs = rbind( docs, c("c3", "Content management system usage of the HTML 5 interface")) # interface system html management
#docs = rbind( docs, c("c4", "Error spotting in HTML: social system versus software system")) # social 2x system html
#docs = rbind( docs, c("c5", "Barriers to access and time spent in social mobile apps")) # access time social
#docs = rbind( docs, c("m1", "The generation of random unordered trees")) # trees
#docs = rbind( docs, c("m2", "A survey of divisive clustering along the intersection of partial trees")) # trees clustering intersection
#docs = rbind( docs, c("m3", "Silhouette widths and height of trees in using agglomerative clustering with Agnes: ")) # trees clustering agglomerative
#docs = rbind( docs, c("m4", "Agglomerative clustering algorithms: a review")) # clustering agglomerative review
#docs = rbind( docs, c("p1", "Learning: the intersection with organisational knowledge"))
#docs = rbind( docs, c("p2", "A transactional perspective on teaching and learning"))
#docs = rbind( docs, c("p3", "Innovations in online learning: moving beyond no significant difference"))
#docs = rbind( docs, c("p4", "Tacit knowledge: the management of organisational learning and innovation"))
#docs = rbind( docs, c("p5", "Knowledge building: theory, pedagogy, and technology"))