
ppl = new("HumanResourceManager", domainmanager=dmgr)

fridolin = ppl$add(name="fridolin")
max = ppl$add(name="max")
joanna = ppl$add(name="joanna")
ou = ppl$add(name="OU")

ppl$ls()

joanna$read("this is a business management text.", purpose="B821")

fridolin$read("this is a business management text.", purpose="B821")

fridolin$write("The strategy framework adopts a combination of both a rational approach to strategy and a process perspective. The rational part is that there is usually a logical and sequential process through the three stages of analysing, choosing and implementing. You have to collect the data and analyse it first, before you can choose a suitable strategy. Then, of course, you need to have chosen your strategy before you can begin implementing it. So far, this is logical, rational and linear: you do stage one, followed by stage two, followed by stage three.However, the reason that the centre of the framework is presented as three interconnected circles is that, in practice, this is not a tidy straight line. Instead, the three stages in the process are all interrelated and iterative. In other words, these three stages need to be performed again and again.Indeed, the process is iterative because it builds on existing organisational knowledge that may emerge gradually over time, and often only when managers begin to ask the right questions. Mintzberg (1987) has argued in his paper ‘Crafting strategy’ that strategies need not be either deliberate or emergent; they are more often both together, for this reason:Purely deliberate strategy precludes learning once the strategy is formulated: emergent strategy fosters it. We can learn from an evolving situation and that learning can be incorporated into an evolving emergent strategy.", purpose="b835", label="Chapter 2: strategy framework & process")

fridolin$write("The first stage of the interrelated strategy process is analysing. It involves examining a variety of frameworks that allow you to develop an understanding of the opportunities and threats facing your organisation from its external environment, as well as an appreciation of the strengths and weaknesses of your organisation in terms of resources and capabilities. You will also need to identify who your primary and secondary stakeholders are, to understand what they may want from the organisation and how to respond to their demands.", purpose="b835", label="Chapter 2.1: analysing")

fridolin$write("The third stage of the strategy process is ‘implementing’. It is often the most difficult stage. Many strategies fail not because the analysis was poor or the strategy inappropriate, but because the implementation of the strategy was badly carried out. Implementing is the stage at which the strategy is translated into action within the organisation. It is therefore the part of strategy in which all levels of the organisation need to become involved and where an understanding by each individual of their role and contribution in the organisation, can contribute to more effective implementation and coordination.The backbone of any implementation process is matching it to the design of the organisational structure and using appropriate management systems for coordination and control. Grant (2010, p. 174) calls these ‘the fundamentals of strategy implementation’. Different types of organisational structure are suited to particular businesses and particular tasks. The organisational structure and control systems suited to a global accounting firm are unlikely to be appropriate for a global fast food chain or an internet start-up. It is also to be expected that the mix of resources required in those organisations will be different, and their cultures too. Managing all these aspects of an organisation is critical for effective strategy implementation, yet all of them are extremely hard to manage or to change.Alongside all these basic aspects of the organisation that need to be managed during implementation, there are also the external forces for change that may sweep in at any moment and cause your wonderful new strategy to become obsolete. These are the four ‘pressures’. We discuss these as the next part of our strategy framework.", purpose="b835", label="Chapter 2.2: implementing")

fridolin$write("Much of the general public discussion of globalisation is based on unclear assumptions. The starting point for understanding this much-discussed and overused concept of globalisation is that in strategy terms it is industries and markets that globalise, not countries. However, when an industry globalises, it undergoes structural shifts, so that the organisations within it find that their position in one country is significantly affected by their position in another country. That is part of the definition of a global industry.Similarly, the impact of global industries and global organisations on the countries in which they operate inevitably creates stronger interconnectedness economically, with potential social and political consequences. This means that as a result of globalisation of industries, greater linkages, interaction and interdependence build up between nations.Global industries require the organisations within them, whether commercial or NFP, to develop global strategies in order to survive. That is what Philips had to do to survive in the consumer electronics industry as products and consumer preferences gradually became global. Its domestic market employment levels and Eurocentric production locations were overtaken by the globalisation of the industry in which it operated.To gain further insight into globalisation, you might want to listen to an audio recording by Susan Segal-Horn. The recording covers various aspects of globalisation, so choose the topics that interest you most.", purpose="b835", label="Chapter 3.2: globalisation")

fridolin$write("To the extent that there is real evidence that many global corporations do frequently use English as the agreed corporate language for all reports and meetings, irrespective of the country in which they take place, then globish may be viewed as a response to that trend. It also lowers barriers to entry by being easier to learn than Standard English. It may be seen as a cultural response to the economic integration of industries and firms across borders. Whether it becomes a true international integrating device or another source of social discrimination remains to be seen.", purpose="b835", label="activity 4: feedback")

ou$write("Discounted cash flow. Any investment gives rise to a stream of future expected cash flows. DCF converts all of these to an equivalent amount of present-day money (or present value) by discounting each future cash flow for the appropriate number of periods (for example, years) by the periodic discount rate. The periodic discount rate is the investor's required rate of return including the time preference rate, a premium for risk and an adjustment for inflation. Having established the present values of each of our possible alternative investments, we now need to compare each present value with the cost of acquiring that investment today. This cost can be expressed as a negative cash flow and included in the DCF calculation at its face value (it is already expressed in present-day money terms, so it does not need to be discounted) by subtracting it from the present value of all the future expected returns. The difference between the positive present value of all the future returns and the negative present value of the initial investment gives us the net present value (NPV) of the overall investment.", purpose="B821", label="Chapter 4.2 Discounted Cash Flow")

ou$write("campaigns are run for marketing reasons or to polish ones image through advertisement, promotions, and more. How to run a campaign? Business owners and companies can hire a marketing manager to take care of this. to make an example: a company has a bad product and just pulled it off the market. now the company has an improved product - and thus wants to run a new marketing campaign. the marketing manager commissions a couple of ads and then sends a team to town with free give aways in a promotion.", purpose="nonesense")

ou$write("The difference between the everyday and the specialised meanings of ‘risk’ is less technical and more radical than in the case of ‘return’. In everyday usage, ‘risk’ is negative – the risk of having a car accident or the risk of losing one's job. If we use ‘risk’ in a positive sense at all, it is only as a result of adopting a consciously ironic tone: ‘There's not much risk of my winning the lottery this week.’ But in the language of finance, ‘risk’ is neutral and refers purely to the possibility that a particular outcome will be different from (that is, either worse or better than) either a single expected outcome or the probability-weighted mean of many possible outcomes. In other words, in financial language ‘risk’ is the same as ‘uncertainty’.", purpose="B821", label="Chapter 1.1")

max$write("this is a text with a giraffe not sure if the word is in though", purpose="B821", label="exam 1")

